DROP TABLE IF EXISTS prescription_medicines CASCADE;
DROP TABLE IF EXISTS prescriptions CASCADE;
DROP TABLE IF EXISTS family_invitations CASCADE;
DROP TABLE IF EXISTS family_memberships CASCADE;
DROP TABLE IF EXISTS families CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS doctor_availability CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS doctors CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP INDEX IF EXISTS idx_users_email_lower;
DROP INDEX IF EXISTS idx_doctor_availability_day_start;
DROP INDEX IF EXISTS idx_appointments_doctor_date;
DROP INDEX IF EXISTS idx_appointments_patient_date;
DROP EXTENSION IF EXISTS "uuid-ossp";
DROP TYPE IF EXISTS sex_type CASCADE;
DROP TYPE IF EXISTS appointment_status CASCADE;
DROP TYPE IF EXISTS family_invitation_status CASCADE;
