/** Prescription PDF generation (pdfkit, A4). */
import PDFDocument from 'pdfkit';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ORGANISATION_NAME, FOOD_TIMING_LABEL } from '../config/constants.js';
import { formatDisplayDate } from '../utils/date.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOGO_PATH = path.resolve(__dirname, '../assets/logo.png');
const PRIMARY = '#1e3a8a';
const MUTED = '#475569';

export function dataUrlToBuffer(dataUrl) {
  const m = /^data:image\/(png|jpe?g);base64,(.+)$/i.exec(dataUrl || '');
  return m ? Buffer.from(m[2], 'base64') : null;
}

const timingText = (it) => {
  const parts = [];
  if (it.morning) parts.push('Morning');
  if (it.afternoon) parts.push('Afternoon');
  if (it.evening) parts.push('Evening');
  if (it.night) parts.push('Night');
  if (it.sos) parts.push('SOS (when required)');
  return parts.join(', ');
};

/**
 * @param {{doctor:{name,speciality,signature}, patient:{name, age, sex}, date:string, items:Array, notes?:string, prescriptionId:number}} data
 * @returns {Promise<Buffer>}
 */
export function buildPrescriptionPdf(data) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48, info: { Title: `Prescription #${data.prescriptionId}`, Author: ORGANISATION_NAME } });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const left = doc.page.margins.left;
    const right = doc.page.width - doc.page.margins.right;
    const width = right - left;

    // ---------- header: logo left of organisation name ----------
    const top = 40;
    if (fs.existsSync(LOGO_PATH)) doc.image(LOGO_PATH, left, top, { width: 58, height: 58 });
    doc.fillColor(PRIMARY).font('Helvetica-Bold').fontSize(21).text(ORGANISATION_NAME, left + 72, top + 8, { width: width - 72 });
    doc.fillColor(MUTED).font('Helvetica').fontSize(10).text('Prescription generated by Sohay Apllication', left 8888+ 72, top + 36);

    // ---------- doctor ----------
    doc.moveDown(0);
    doc.y = top + 78;
    doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(14).text(data.doctor.name, left, doc.y);
    doc.fillColor(MUTED).font('Helvetica').fontSize(11).text(data.doctor.speciality);

    // ---------- horizontal line ----------
    doc.moveDown(0.6);
    doc.moveTo(left, doc.y).lineTo(right, doc.y).lineWidth(1.5).strokeColor(PRIMARY).stroke();
    doc.moveDown(0.8);

    // ---------- patient ----------
    const py = doc.y;
    const col = width / 3;
    const field = (label, value, x) => {
      doc.fillColor(MUTED).font('Helvetica').fontSize(9).text(label.toUpperCase(), x, py, { width: col - 8 });
      doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(12).text(value, x, py + 12, { width: col - 8 });
    };
    field('Patient name', data.patient.name, left);
    field('Age', `${data.patient.age} years${data.patient.sex ? ` / ${data.patient.sex}` : ''}`, left + col);
    field('Date', formatDisplayDate(data.date), left + col * 2);
    doc.y = py + 40;
    doc.x = left;

    // ---------- medicines ----------
    doc.fillColor(PRIMARY).font('Helvetica-Bold').fontSize(22).text('Rx', left, doc.y);
    doc.moveDown(0.3);
    const SIGNATURE_ZONE = 120;
    data.items.forEach((it, i) => {
      const blockTop = doc.y;
      if (blockTop > doc.page.height - doc.page.margins.bottom - SIGNATURE_ZONE) { doc.addPage(); }
      const y0 = doc.y;
      doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(12).text(`${i + 1}. ${it.medicineName}`, left + 8, y0, { width: width - 16 });
      doc.fillColor('#1f2937').font('Helvetica').fontSize(10.5);
      doc.text(`Dose: ${it.dose}`, left + 22, doc.y + 2, { width: width - 30 });
      doc.text(`When: ${timingText(it) || '-'}   |   ${FOOD_TIMING_LABEL[it.foodTiming] || it.foodTiming}`, left + 22, doc.y + 1, { width: width - 30 });
      if (it.instructions) doc.fillColor(MUTED).font('Helvetica-Oblique').text(`Note: ${it.instructions}`, left + 22, doc.y + 1, { width: width - 30 });
      const y1 = doc.y + 6;
      doc.roundedRect(left, y0 - 6, width, y1 - y0 + 6, 6).lineWidth(0.6).strokeColor('#cbd5e1').stroke();
      doc.y = y1 + 8;
    });

    if (data.notes) {
      doc.moveDown(0.5);
      doc.fillColor(PRIMARY).font('Helvetica-Bold').fontSize(11).text('Advice', left, doc.y);
      doc.fillColor('#1f2937').font('Helvetica').fontSize(10.5).text(data.notes, left, doc.y + 2, { width });
    }

    // ---------- signature (bottom right of the last page) ----------
    const sigW = 160; const sigH = 60;
    const sigX = right - sigW;
    const sigY = doc.page.height - doc.page.margins.bottom - sigH - 34;
    if (doc.y > sigY - 10) doc.addPage();
    const sig = dataUrlToBuffer(data.doctor.signature);
    if (sig) {
      try { doc.image(sig, sigX, sigY, { fit: [sigW, sigH], align: 'right', valign: 'bottom' }); } catch { /* ignore broken image */ }
    }
    doc.moveTo(sigX, sigY + sigH + 4).lineTo(right, sigY + sigH + 4).lineWidth(0.8).strokeColor('#94a3b8').stroke();
    doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(10).text(data.doctor.name, sigX, sigY + sigH + 8, { width: sigW, align: 'right' });
    doc.fillColor(MUTED).font('Helvetica').fontSize(8.5).text(`Prescription #${data.prescriptionId}`, left, sigY + sigH + 10, { width: 200 });

    doc.end();
  });
}
