import {pool} from '../config/db.js';
import {hashPassword} from '../services/authService.js';
import {listDoctors,listPatients,activeDoctors,createUser,createDoctorRole,createAvailability,deleteAvailability,updateDoctor,updateDoctorRole,getDoctor,getAvailability,setDisabled,upcomingAppointment,appointmentById,doctorAvailabilityForDate,activeDoctorSlotsForDate,activePatientSlotsForDate,rescheduleAppointment,emailConflict} from '../../scripts/sql/adminQueries.js';
import {beginTransaction,commitTransaction,rollbackTransaction} from '../../scripts/sql/generalQueries.js';
import {allowedSexes,strongPassword,timeSlots,validDate,availabilitySlots,validateAvailability,activeSlotKeys,endTime} from '../utils/validation.js';
import {sendAppointmentMail} from '../services/emailService.js';
function verifyRescheduleSlot(date,start){if(!validDate(date)||date<new Date().toISOString().slice(0,10))throw new Error('Invalid appointment date.');if(!timeSlots.includes(start))throw new Error('Invalid 30-minute slot.');}
export async function doctors(req,res){const r=await pool.query(listDoctors);res.json({items:r.rows})}
export async function patients(req,res){const r=await pool.query(listPatients,[false]);res.json({items:r.rows})}
export async function patientVisibleDoctors(req,res){const r=await pool.query(activeDoctors,[false]);res.json({items:r.rows})}
export async function doctorDetails(req,res){const d=await pool.query(getDoctor,[req.params.id,1]);if(!d.rowCount)return res.status(404).json({message:'Doctor not found.'});const a=await pool.query(getAvailability,[req.params.id]);res.json({doctor:d.rows[0],availability:a.rows})}
export async function saveDoctor(req,res){const b=req.body;const id=b.id||req.params.id; if(!allowedSexes.has(b.sex))return res.status(400).json({message:'Invalid sex value.'});validateAvailability(b.availability);if(id){if(b.password&&(!strongPassword.test(b.password)||b.password!==b.confirmPassword))return res.status(400).json({message:'Invalid password or confirmation.'})}else if(!strongPassword.test(String(b.password||''))||b.password!==b.confirmPassword)return res.status(400).json({message:'Doctor password does not meet password rules.'});const email=String(b.email).trim().toLowerCase();const conflict=await pool.query(emailConflict,[email,id||0,1]);if(conflict.rowCount)return res.status(409).json({message:'Email is already used.'});const client=await pool.connect();try{await client.query(beginTransaction);let doctorId=id;if(id){await client.query(updateDoctor,[String(b.name).trim(),email,b.password?await hashPassword(b.password):null,id]);await client.query(updateDoctorRole,[b.sex,String(b.speciality).trim(),id]);await client.query(deleteAvailability,[id])}else{const u=await client.query(createUser,[String(b.name).trim(),email,await hashPassword(b.password),false]);doctorId=u.rows[0].id;await client.query(createDoctorRole,[doctorId,b.sex,String(b.speciality).trim()])}for(const a of b.availability)await client.query(createAvailability,[doctorId,Number(a.weekday),a.startTime,a.endTime]);await client.query(commitTransaction);console.log('[ADMIN] doctor saved',email);res.status(id?200:201).json({message:id?'Doctor updated successfully.':'Doctor added successfully.'})}catch(e){await client.query(rollbackTransaction);throw e}finally{client.release()}}
export async function toggleDoctor(req,res){await pool.query(setDisabled,[Boolean(req.body.disabled),req.params.id,1]);console.log('[ADMIN] doctor status',req.params.id,req.body.disabled);res.json({message:req.body.disabled?'Doctor disabled.':'Doctor enabled.'})}
export async function upcoming(req,res){const r=await pool.query(upcomingAppointment,[req.query.patientId,req.query.doctorId,'scheduled','rescheduled',1]);res.json({appointment:r.rows[0]||null})}
export async function availableSlots(req,res){const date=String(req.query.date);verifyRescheduleSlot(date,String(req.query.startTime||'00:00'));const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();const [av,db,pb]=await Promise.all([pool.query(doctorAvailabilityForDate,[req.query.doctorId,weekday]),pool.query(activeDoctorSlotsForDate,[req.query.doctorId,date,'scheduled','rescheduled']),pool.query(activePatientSlotsForDate,[req.query.patientId,date,'scheduled','rescheduled'])]);const blocked=new Set([...db.rows,...pb.rows].map(x=>String(x.start_time).slice(0,5)));res.json({items:availabilitySlots(av.rows).filter(x=>!blocked.has(x))})}
export async function reschedule(req,res){const b=req.body;verifyRescheduleSlot(b.date,b.startTime);const r=await pool.query(appointmentById,[b.appointmentId,1]);if(!r.rowCount)return res.status(404).json({message:'Appointment not found.'});const a=r.rows[0];const weekday=new Date(`${b.date}T00:00:00Z`).getUTCDay();const av=await pool.query(doctorAvailabilityForDate,[a.doctor_id,weekday]);if(!availabilitySlots(av.rows).includes(b.startTime))return res.status(400).json({message:'Selected time is outside doctor availability.'});const keys=activeSlotKeys(a.patient_id,a.doctor_id,b.date,b.startTime);try{const u=await pool.query(rescheduleAppointment,[b.date,b.startTime,endTime(b.startTime),keys.doctor,keys.patient,a.status==='rescheduled'?'rescheduled':'rescheduled',b.appointmentId,'scheduled','rescheduled']);if(!u.rowCount)return res.status(409).json({message:'Appointment can no longer be rescheduled.'})}catch(e){if(e.code==='23505')return res.status(409).json({message:'Selected time conflicts with another active appointment.'});throw e}await sendAppointmentMail({to:a.patient_email,name:a.patient_name,doctor:a.doctor_name,speciality:a.speciality,date:b.date,time:b.startTime,roomId:a.room_id,action:'rescheduled'}).catch(e=>console.error('[MAIL] reschedule',e));res.json({message:'Appointment rescheduled successfully.'})}
