import {pool} from '../config/db.js';
import {familyMemberships,createFamily,addFamilyMember,isFamilyMember,sameFamilyMember,patientByEmail,familyInvitation,pendingInvitations,invitationById,updateInvitationStatus,doctorAvailabilityForDate,activeDoctorById,activeDoctorSlotsForDate,activePatientSlotsForDate,createAppointment,appointmentBookingInfo,patientAppointments,cancelAppointment,prescriptionByPatient} from '../../scripts/sql/patientQueries.js';
import {beginTransaction,commitTransaction,rollbackTransaction} from '../../scripts/sql/generalQueries.js';
import {availabilitySlots,validDate,timeSlots,endTime,activeSlotKeys} from '../utils/validation.js';
import {createRoom} from '../services/jitsiService.js';
import {sendFamilyInviteMail,sendFamilyResponseMail,sendAppointmentMail} from '../services/emailService.js';
import {signedPdfUrl} from '../services/s3Service.js';
export async function families(req,res){const r=await pool.query(familyMemberships,[req.user.sub]);res.json({items:r.rows})}
export async function createFamilyGroup(req,res){const name=String(req.body.familyName||'').trim();if(!name)return res.status(400).json({message:'Family name is required.'});const c=await pool.connect();try{await c.query(beginTransaction);const f=await c.query(createFamily,[req.user.sub,name]);await c.query(addFamilyMember,[f.rows[0].id,req.user.sub]);await c.query(commitTransaction);res.status(201).json({message:'Family created successfully.'})}catch(e){await c.query(rollbackTransaction);throw e}finally{c.release()}}
export async function inviteFamilyMember(req,res){const familyId=Number(req.body.familyId);const email=String(req.body.email||'').trim().toLowerCase();const m=await pool.query(isFamilyMember,[familyId,req.user.sub]);if(!m.rows[0]?.member)return res.status(403).json({message:'You are not a member of this family.'});const target=await pool.query(patientByEmail,[email,false,1]);if(!target.rowCount)return res.status(404).json({message:'Patient email not found or patient is disabled.'});if(Number(target.rows[0].user_id)===Number(req.user.sub))return res.status(400).json({message:'You cannot invite yourself.'});const i=await pool.query(familyInvitation,[familyId,req.user.sub,target.rows[0].user_id,'pending']);await sendFamilyInviteMail({to:target.rows[0].email,inviter:req.user.name}).catch(e=>console.error('[MAIL] family invite',e));res.status(201).json({message:'Family invitation sent.',invitationId:i.rows[0].id})}
export async function invitations(req,res){const r=await pool.query(pendingInvitations,[req.user.sub,'pending']);res.json({items:r.rows})}
export async function respondInvitation(req,res){const r=await pool.query(invitationById,[req.params.id,1]);if(!r.rowCount)return res.status(404).json({message:'Invitation not found.'});const status=req.body.accept?'accepted':'rejected';const u=await pool.query(updateInvitationStatus,[status,req.params.id,req.user.sub,'pending']);if(!u.rowCount)return res.status(409).json({message:'Invitation has already been processed.'});if(status==='accepted')await pool.query(addFamilyMember,[r.rows[0].family_id,req.user.sub]);await sendFamilyResponseMail({to:r.rows[0].inviter_email,member:r.rows[0].invitee_name,status}).catch(e=>console.error('[MAIL] family response',e));res.json({message:`Invitation ${status}.`})}
export async function availability(req,res){const date=String(req.query.date);const beneficiary=Number(req.query.beneficiaryPatientId||req.user.sub);if(!validDate(date))return res.status(400).json({message:'Invalid date.'});if(beneficiary!==Number(req.user.sub)){const m=await pool.query(sameFamilyMember,[1,req.user.sub,beneficiary]);if(!m.rows[0]?.member)return res.status(403).json({message:'Selected patient is not in your family.'})}const d=await pool.query(activeDoctorById,[req.query.doctorId,false,1]);if(!d.rowCount)return res.status(404).json({message:'Doctor is not available for booking.'});const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();const [av,db,pb]=await Promise.all([pool.query(doctorAvailabilityForDate,[req.query.doctorId,weekday]),pool.query(activeDoctorSlotsForDate,[req.query.doctorId,date,'scheduled','rescheduled']),pool.query(activePatientSlotsForDate,[beneficiary,date,'scheduled','rescheduled'])]);const blocked=new Set([...db.rows,...pb.rows].map(x=>String(x.start_time).slice(0,5)));res.json({items:availabilitySlots(av.rows).filter(x=>!blocked.has(x))})}
export async function book(req,res){const b=req.body;const beneficiary=Number(b.beneficiaryPatientId||0);const date=String(b.date);const start=String(b.startTime);if(!beneficiary||!validDate(date)||date<new Date().toISOString().slice(0,10))return res.status(400).json({message:'Appointment date must be today or a future date.'});if(!timeSlots.includes(start))return res.status(400).json({message:'Invalid 30-minute time slot.'});if(beneficiary!==Number(req.user.sub)){const familyOk=await pool.query(sameFamilyMember,[1,req.user.sub,beneficiary]);if(!familyOk.rows[0]?.member)return res.status(403).json({message:'Selected patient is not in your family.'})}const d=await pool.query(activeDoctorById,[b.doctorId,false,1]);if(!d.rowCount)return res.status(404).json({message:'Doctor is not available for booking.'});const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();const av=await pool.query(doctorAvailabilityForDate,[b.doctorId,weekday]);if(!availabilitySlots(av.rows).includes(start))return res.status(400).json({message:'Selected time is outside doctor availability.'});const room=createRoom();const keys=activeSlotKeys(beneficiary,b.doctorId,date,start);try{const r=await pool.query(createAppointment,[req.user.sub,beneficiary,b.doctorId,date,start,endTime(start),'scheduled',room.roomId,keys.doctor,keys.patient]);const info=await pool.query(appointmentBookingInfo,[r.rows[0].id,1]);await sendAppointmentMail({to:info.rows[0].patient_email,name:info.rows[0].patient_name,doctor:info.rows[0].doctor_name,speciality:info.rows[0].speciality,date,time:start,roomId:info.rows[0].room_id,action:'booked'}).catch(e=>console.error('[MAIL] booking',e));res.status(201).json({message:'Appointment booked successfully.',roomId:room.roomId})}catch(e){if(e.code==='23505')return res.status(409).json({message:'The selected time is already booked for the doctor or patient.'});throw e}}
export async function appointments(req,res){const r=await pool.query(patientAppointments,[req.user.sub]);res.json({items:r.rows})}
export async function cancel(req,res){const r=await pool.query(cancelAppointment,['cancelled',req.params.id,req.user.sub,'scheduled','rescheduled']);if(!r.rowCount)return res.status(409).json({message:'Appointment is not eligible for cancellation.'});res.json({message:'Appointment cancelled successfully.'})}
export async function prescriptionDownload(req,res){const r=await pool.query(prescriptionByPatient,[req.params.id,req.user.sub,1]);if(!r.rowCount)return res.status(404).json({message:'Prescription not found.'});if(Number(r.rows[0].patient_id)!==Number(req.user.sub))return res.status(403).json({message:'You are not allowed to access this prescription.'});res.json({url:await signedPdfUrl(r.rows[0].pdf_key)})}
